#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/10-loolwsd-init ]
do
  sleep 1
done

if [ ! -f /tmp/state/10-loolwsd ]; then
  touch /tmp/state/10-loolwsd
fi

### Set Debug Mode
if [ "$DEBUG_MODE" = "TRUE" ] || [ "$DEBUG_MODE" = "true" ]; then
    set -x
fi

echo '**'
echo '** [libreoffice-online] Starting Libreoffice Online Web Services daemon'
exec s6-setuidgid lool /opt/lool/bin/loolwsd --version --o:sys_template_path=/opt/lool/systemplate --o:lo_template_path=/opt/libreoffice --o:child_root_path=/opt/lool/jails --o:file_server_root_path=/opt/lool/share/loolwsd storage.filesystem[@allow]=true --o:admin_console.username=${ADMIN_USER} --o:admin_console.password=${ADMIN_PASS} ${EXTRA_OPTIONS} >> /var/log/lool/loolwsd.log
