services:
  collabora-online-app:
    image: tiredofit/collabora-online
    container_name: collabora-online-app
    hostname: online.example.com
    cap_add:
      - MKNOD
      - NET_ADMIN
    privileged: true
    labels:
      - traefik.enable=true
      - traefik.http.routers.collabora-online-app.rule=Host(`online.example.com`)
      - traefik.http.services.collabora-online-app.loadbalancer.server.port=9980
    volumes:
      - ./logs:/logs
    environment:
      - TIMEZONE=America/Vancouver
      - CONTAINER_NAME=collabora-online-app

      - ADMIN_USER=admin
      - ADMIN_PASS=collabora-online

      - ALLOWED_HOSTS=host1.example.org,host2.example.org,host1.example.net

      - ENABLE_TLS=FALSE
      - ENABLE_TLS_REVERSE_PROXY=TRUE

      - INTERFACE=tabbed
      - LOG_TYPE=FILE
    networks:
      - proxy
      - services
    restart: always

networks:
  proxy:
    external: true
  services:
    external: true
