#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service defaults single
PROCESS_NAME="collabora-online"

check_container_initialized
check_service_initialized init
liftoff

export LC_CTYPE=en_US.UTF-8

print_start "Starting Libreoffice Online Web Services daemon"
exec sudo -u cool /opt/cool/bin/coolwsd \
                  --version \
                  --o:sys_template_path=/opt/cool/systemplate \
                  --o:lo_template_path=/opt/libreoffice \
                  --o:child_root_path=/opt/cool/child-roots \
                  --o:file_server_root_path=/opt/cool/share/coolwsd storage.filesystem[@allow]=true \
                  --o:admin_console.username=${ADMIN_USER} \
                  --o:admin_console.password=${ADMIN_PASS} \
                  ${EXTRA_OPTIONS} >> ${LOG_PATH}/${LOG_FILE}
